services:
  - type: worker
    name: apnaex-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m Extractor
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_ID2
        sync: false
      - key: MONGO_URL
        sync: false
      - key: PREMIUM_LOGS
        sync: false
      - key: THUMB_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.11
